### ISSUE TITLE
Fantasy Land Specification

### ISSUE THREAD

**Issue by johnteee** [TeaEntityLab/fpEs#5]
https://github.com/rpominov/static-land/blob/master/docs/spec.md

(object-based version https://github.com/fantasyland/fantasy-land)

**Comment by johnteee** [comment]
Somehow it is a nice reference, however it's no need to implement an algebra system...

@alfmoh how do you think about it

**Comment by alfmoh** [comment]
Yeah, the algebraic system is cool but it will be nice to focus on the current system now and finish with that before trying out another system
